CREATE TABLE IF NOT EXISTS items (
    id CHAR(36) NOT NULL UNIQUE,
    user_id INT NOT NULL,
    type VARCHAR(50) NOT NULL,
    ciphertext TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);